### PR TITLE
Fix: undefined method `timestamped_migrations' for ActiveRecord::Base:Class

### PR DESCRIPTION
**Pull request by graysonchen**
```
 rails g acts_as_favoritor

      create  config/initializers/acts_as_favoritor.rb
/Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/activerecord-7.1.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `timestamped_migrations' for ActiveRecord::Base:Class (NoMethodError)
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/acts_as_favoritor-6.0.1/lib/generators/acts_as_favoritor_generator.rb:13:in `next_migration_number'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/generators/migration.rb:43:in `set_migration_assigns!'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/generators/migration.rb:59:in `migration_template'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/acts_as_favoritor-6.0.1/lib/generators/acts_as_favoritor_generator.rb:26:in `create_migration_file'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/invocation.rb:134:in `block in invoke_all'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/invocation.rb:134:in `each'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/invocation.rb:134:in `map'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/invocation.rb:134:in `invoke_all'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/group.rb:232:in `dispatch'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/base.rb:584:in `start'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/generators.rb:261:in `invoke'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/commands/generate/generate_command.rb:26:in `perform'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
  from <internal:/Users/xxxxxx/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
  from <internal:/Users/xxxxxx/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
  from /Users/xxxxxx/.rvm/gems/ruby-3.2.1/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from bin/rails:4:in `<main>'
```

### CODE REVIEW

**Comment by graysonchen** [comment]
Hey @jonhue let me know if you have any questions, here

**Comment by jonhue** [comment]
Thank you for your contribution @graysonchen ! Sorry for taking some time to get to it!

**Comment by estebanutz** [comment]
@graysonchen @jonhue I'm getting this same error running ruby 3.2.0 and activerecord-7.1.3 anything I'm missing? I just installed v 6.0.1. Thanks!

**Comment by graysonchen** [comment]
@estebanutz try to upgrade gem locally from GitHub. `gem 'acts_as_favoritor', github: 'jonhue/acts_as_favoritor'`

@jonhue  Could you release 6.0.2 https://github.com/jonhue/acts_as_favoritor/pull/569 and update gem https://rubygems.org/gems/acts_as_favoritor

**Comment by estebanutz** [comment]
@graysonchen Thanks! that worked! just FYI I had to do this again on the migration file generated: https://github.com/jonhue/acts_as_favoritor/discussions/238

**Pull request merged**
